name: sample-workflow
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - run: |
          java -version
          echo "--------------------"
          echo "JAVA_HOME: $JAVA_HOME"
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - run: |
          java -version
          echo "--------------------"
          echo "JAVA_HOME: $JAVA_HOME"
